### ISSUE TITLE
Error loading UI in Brave Browser

### ISSUE THREAD

**Issue by theoturner** [SprawlNetwork/sprawl-prototype#1]
MetaMask is enabled with Ropsten ETH. Chrome works fine.

UI error:
```
An error occurred, please reload the page and try again
If this problem persists please report it
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:202:19)
    at invokeGuardedCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:248:31)
    at commitRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:16075:7)
    at completeRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17463:3)
    at performWorkOnRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17391:9)
    at performWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17295:7)
    at performSyncWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17267:3)
    at requestWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17155:5)
    at scheduleWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:16949:5)
    at Object.enqueueSetState (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:11623:5)
      
Components stack:
    in UnlockMetaMaskMessage (created by AppComponent)
    in AppComponent (created by Connect(AppComponent))
    in Connect(AppComponent)
    in ErrorsBoundaryComponent (created by Connect(ErrorsBoundaryComponent))
    in Connect(ErrorsBoundaryComponent)
    in Provider

```

Browser console error:
```
Uncaught TypeError: Cannot read property 'enable' of undefined
    at UnlockMetaMaskMessage.componentDidMount (webpack-internal:///./components/UnlockMetaMaskMessage.js:8)
    at commitLifeCycles (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:14685)
    at commitAllLifeCycles (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:15905)
    at HTMLUnknownElement.callCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:145)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:195)
    at invokeGuardedCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:248)
    at commitRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:16075)
    at completeRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17463)
    at performWorkOnRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17391)
    at performWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17295)
webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:14550 The above error occurred in the <UnlockMetaMaskMessage> component:
    in UnlockMetaMaskMessage (created by AppComponent)
    in AppComponent (created by Connect(AppComponent))
    in Connect(AppComponent)
    in ErrorsBoundaryComponent (created by Connect(ErrorsBoundaryComponent))
    in Connect(ErrorsBoundaryComponent)
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorsBoundaryComponent.
logCapturedError @ webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:14550
webpack-internal:///./containers/ErrorsBoundary.js:20 Uncaught error got into the error boundary Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:202)
    at invokeGuardedCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:248)
    at commitRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:16075)
    at completeRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17463)
    at performWorkOnRoot (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17391)
    at performWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17295)
    at performSyncWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17267)
    at requestWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:17155)
    at scheduleWork (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:16949)
    at Object.enqueueSetState (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:11623) Object
```

**Comment by alcuadrado** [comment]
Hi Theo! Thanks for reporting this. 

It seems to be related to a recent  metamask's api change. I'll fix it later today or tomorrow.

**Comment by alcuadrado** [comment]
I just pushed a fix for this!

I'll close the issue, but feel free to reopen the issue if the error persists.
